const dummayData = [
  {
    id: 0,
    date: '25 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$30',
  },
  {
    id: 1,
    date: '26 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$30',
  },
  {
    id: 2,
    date: '27 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$40',
  },
  {
    id: 3,
    date: '28 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$50',
  },
  {
    id: 4,
    date: '29 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$60',
  },
  {
    id: 5,
    date: '30 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$80',
  },
  {
    id: 5,
    date: '30 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$80',
  },
  {
    id: 5,
    date: '30 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$80',
  },
  {
    id: 5,
    date: '30 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$80',
  },
  {
    id: 5,
    date: '30 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$80',
  },
  {
    id: 5,
    date: '30 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$80',
  },
  {
    id: 5,
    date: '30 JAN 2012',
    name: 'Rowdy Rathore',
    address: 'Ambale 23 sector',
    price: '$80',
  },
]
export default dummayData